name = "nodewarden"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# KV Namespace for storing vault data
[[kv_namespaces]]
binding = "VAULT"
id = "d6f8eca50b334e8f9275758dfe800254"

# R2 Bucket for storing attachments
[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "nodewarden-attachments"
